#!/usr/bin/env bash
# while on my machine, setup env

set -e
set -x

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}"

declare CUBING_JSON
CUBING_JSON="${THIS_DIR}/cubing.json"
declare -rx CUBING_JSON

if [[ ! -e "${CUBING_JSON}" ]]; then
	printf '%s JSON file doesnt exist\n' "${CUBING_JSON}" 1>&2
	exit 1
fi

exec mix phx.server
