#!/bin/bash -eu
# while on my machine, start the development servers

# echo out API keys -u flag checks if they're unset
echo -e "Trakt API Key: ${TRAKT_API_KEY}"
echo -e "TMDB API Key: ${TMDB_API_KEY}"

# https://sean.fish/d/.local/scripts/linux/services?dark
sudo services start

# https://github.com/seanbreckenridge/albums
python3 "${REPOS}/albums/server/app.py" &
# https://github.com/seanbreckenridge/wca_userinfo
"${REPOS}/wca_userinfo/run_server" &
# https://github.com/seanbreckenridge/docker-jikan
cd "${REPOS}/docker-jikan" && ./run &

mix phx.server

kill $(jobs -p)
