#!/usr/bin/env bash
# while on my machine, setup env

set -e
set -x

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}"

declare CUBING_JSON
CUBING_JSON="${THIS_DIR}/data/cubing.json"
declare -rx CUBING_JSON

GUESTBOOK_JSON_PATH="${THIS_DIR}/data/guestbook.json"
PAGE_HITS_OFFSET='150'
export GUESTBOOK_JSON_PATH PAGE_HITS_OFFSET

# clean deps
mix deps.clean glue
exec mix phx.server
