#!/bin/bash -exu
# use https://github.com/seanbreckenridge/darker_errors
# to generate dark-themed error pages as fallbacks

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
TARGET_DIR="${THIS_DIR}/lib/glue_web/templates/error"
TMP_DIR='/tmp/darker_temp'

rm -rf "$TMP_DIR"
mkdir -p "$TMP_DIR"
rm -rf "$TARGET_DIR"
mkdir -p "$TARGET_DIR"

darker_errors -output-dir "$TMP_DIR" '404:ERROR_AFTER_MSG:<p>Click <a href="/">here</a> to go back home.<p>' 'ERROR_TITLE:sean - STATUS_MSG'

# minify HTML
html-minifier --collapse-whitespace --minify-css --minify-js --remove-attribute-quotes --remove-comments --remove-empty-attributes --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --remove-tag-whitespace --input-dir "${TMP_DIR}" --output-dir "${TARGET_DIR}" --file-ext html

# rename files
find "$TARGET_DIR" -type f -exec mv {} {}.eex \;
