#!/bin/bash

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

HASH="$(git rev-parse HEAD | cut -c -8)"
printf 'export const hash = "%s"' "${HASH}" >./assets/frontend/build.tsx
