#!/bin/bash -e
# accepts the secret file from https://github.com/seanbreckenridge/vps
# see the secret.dist file there

# default location on my server
declare FILEPATH DEFAULT_SECRET
readonly DEFAULT_SECRET="${REPOS:-${HOME}}/vps/secret"

if [[ -n "$2" ]]; then
	FILEPATH="$2"
else
	if [[ -e "${DEFAULT_SECRET}" ]]; then
		FILEPATH="${DEFAULT_SECRET}"
	else
		echo "Error: Pass JSON config file as second argument" 1>&2
		exit 1
	fi
fi

if [[ ! -r "${FILEPATH}" ]]; then
	printf "No such file: %s\n" "$1" 1>&2
	exit 1
fi

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}"

mkdir -p ./data

declare CUBING_JSON GUESTBOOK_JSON_PATH
CUBING_JSON="${THIS_DIR}/data/cubing.json"
GUESTBOOK_JSON_PATH="${THIS_DIR}/data/guestbook.json"

declare -rx CUBING_JSON GUESTBOOK_JSON_PATH

if [[ ! -e "${CUBING_JSON}" ]]; then
	printf '%s JSON file doesnt exist\n' "${CUBING_JSON}" 1>&2
	exit 1
fi

if [[ ! -e "${GUESTBOOK_JSON_PATH}" ]]; then
	printf '%s JSON file doesnt exist\n' "${GUESTBOOK_JSON_PATH}" 1>&2
	exit 1
fi

declare GLUE_DATABASE_PATH GLUE_SECRET_KEY_BASE MIX_ENV
GLUE_DATABASE_PATH="${THIS_DIR}/data/prod.sqlite"
GLUE_SECRET_KEY_BASE="$(jq -r '.glue_secret' "${FILEPATH}")"
MIX_ENV=prod
export GLUE_DATABASE_PATH GLUE_SECRET_KEY_BASE MIX_ENV

case "$1" in
# drop into an interactive shell after loading environment secrets
--shell)
	echo "Dropping into interactive shell with secrets..."
	bash
	exit 0
	;;
--iex)
	# drop into iex after loading environment secrets
	iex -S mix
	exit 0
	;;
--epochs)
	mix run -e Glue.PageHits.page_hit_epochs || exit $?
	exit 0
	;;
--approve-comments)
	# approve any new comments
	mix run -e Glue.GuestBookComments.CLI.main || exit $?
	exit 0
	;;
--review-comments)
	# re-approve/deny all comments
	mix run -e Glue.GuestBookComments.CLI.all || exit $?
	exit 0
	;;
--print-count)
	mix run -e Glue.GuestBookComments.CLI.new_count || exit $?
	exit 0
	;;
--print-new-comments)
	mix run -e Glue.GuestBookComments.CLI.print_new_comments || exit $?
	exit 0
	;;
--edit-comment)
	mix run -e Glue.GuestBookComments.CLI.edit_comment || exit $?
	exit 0
	;;
--run)
	:
	;;

*)
	echo "Must specify one of:"
	grep -P '^\s*--?[\w-]+\)' "$(realpath "$0")" | tr -d '); '
	exit 1
	;;
esac

mix deps.get --only prod
mix compile
mix phx.digest.clean

cd ./assets
yarn
yarn deploy
cd "${THIS_DIR}"
exec mix prod.server
