#!/bin/bash -e
# accepts the secret file from https://github.com/seanbreckenridge/vps
# see the secret.dist file there

# defualt location on my server
declare FILEPATH DEFAULT_SECRET
readonly DEFAULT_SECRET="${REPOS:-${HOME}}/vps/secret"

if [[ -n "${2}" ]]; then
	FILEPATH="${2}"
else
	if [[ -e "${DEFAULT_SECRET}" ]]; then
		FILEPATH="${DEFAULT_SECRET}"
	else
		echo "Error: Pass JSON config file as second argument" 1>&2
		exit 1
	fi
fi

if [[ ! -r "${FILEPATH}" ]]; then
	printf "No such file: %s\n" "$1" 1>&2
	exit 1
fi

declare GLUE_DATABASE_URI GLUE_SECRET_KEY_BASE TRAKT_API_KEY TMDB_API_KEY MIX_ENV
GLUE_DATABASE_URI="$(jq -r '.postgres_uri' "$FILEPATH")"
GLUE_SECRET_KEY_BASE="$(jq -r '.glue_secret' "$FILEPATH")"
TRAKT_API_KEY="$(jq -r '.trakt_api_key' "$FILEPATH")"
TMDB_API_KEY="$(jq -r '.tmdb_api_key' "$FILEPATH")"
MIX_ENV=prod
export GLUE_DATABASE_URI GLUE_SECRET_KEY_BASE TRAKT_API_KEY TMDB_API_KEY MIX_ENV


case "$1" in
# drop into an interactive shell after loading environment secrets
--shell)
	echo "Dropping into interactive shell with secrets..."
	bash
	exit 0
	;;
--iex)
	# drop into iex after loading environment secrets
	iex -S mix
	exit 0
	;;
--run)
	:
	;;

*)
	echo "Must specify one of:"
	grep -P '^\s*--?\w+\)' "$(realpath "$0")" | tr -d '); '
	exit 1
	;;
esac

mix deps.get --only prod
mix compile

npm install --prefix ./assets 2>/dev/null
npm run deploy --prefix ./assets 2>/dev/null
exec mix prod.server
