#!/bin/bash -ex
# helper scrpit to lint, commit, push and restart server

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "$THIS_DIR"

commit() {
	if [[ -n "$1" ]]; then
		git commit -m "$*"
		return $?
	else
		git commit # prompt for editor
		return $?
	fi
}

./generate_build_hash || exit $?
./lint || exit $?
git add -A &&
	commit "$@" &&
	git push

# restart remote server
ssh vultr "cd ./code/glue && git pull && ~/vps/super --ctl restart glue-server"
