#!/bin/bash -ex
# helper script to format/create build hash

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "$THIS_DIR"

commit() {
	if [[ -n "$1" ]]; then
		git commit -m "$*"
		return $?
	else
		git commit # prompt for editor
		return $?
	fi
}

./lint || exit $?
git add -A &&
	commit "$@" &&
	git push
