#!/usr/bin/env bash
# use https://github.com/seanbreckenridge/wca_userinfo
# to fetch my wca results
# save it to a file and sync it to the remote dir
#
# this runs every few weeks by a block in my
# https://sean.fish/d/.local/scripts/linux/housekeeping?dark

set -e
set -o pipefail

wait-for-internet

echo 'Updating cubing record file...'

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

havecmd wca_userinfo || cargo install --git "https://github.com/seanbreckenridge/wca_userinfo"

mkdir -p ./data
wca_userinfo 2017BREC02 | jq >./data/cubing.json
scp ./data/cubing.json vultr:~/code/glue/data/
